### ISSUE TITLE
API Keys in your Repo

### ISSUE THREAD

**Issue by bmw2621** [mikeejazmines/tinder-clone#1]
I was just surfing around looking for how people have implemented a Tinder clone and found your repo.

You should remove your API Keys in `src/firebase.js` otherwise people could spam your firebase account and run up costs.

Put them in a `.env` file, add it to your `.gitignore` and call them in with the `dotenv` package

**Comment by godofthunder8756** [comment]
Hey @mikeejazmines hide your Firebase config!

**Comment by kamleshjoshi8102** [comment]
> I was just surfing around looking for how people have implemented a Tinder clone and found your repo.
> 
> You should remove your API Keys in `src/firebase.js` otherwise people could spam your firebase account and run up costs.
> 
> Put them in a `.env` file, add it to your `.gitignore` and call them in with the `dotenv` package

Thanks I was about to deploy my tinder clone 😅

**Comment by mikeejazmines** [comment]
I haven't gone on github for a while but thank you for your messages :)

@bmw2621 @godofthunder8756 @kamleshjoshi8102
